Importing the libraries

In [1]:
#Importing the necessary Visualization Libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import sklearn
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly.offline
import cufflinks as cf
import pandas as pd
import numpy as np
import chart_studio.plotly as py
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px
%matplotlib inline
init_notebook_mode(connected=True)
cf.go_offline()

# Importing Sklearn
# Regression
# We import Scikit Learn
lm = LinearRegression()


In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import itertools
import matplotlib.pyplot as plt
from matplotlib.ticker import NullFormatter
import matplotlib.ticker as ticker
%matplotlib inline


Importing the dataset

In [3]:
df1 = 'C:/Users/User/Downloads/tele_customer.csv'
df = pd.read_csv(df1)
df

region  tenure  age  marital  address  income  ed  employ  retire  \
0         2      13   44        1        9    64.0   4       5     0.0   
1         3      11   33        1        7   136.0   5       5     0.0   
2         3      68   52        1       24   116.0   1      29     0.0   
3         2      33   33        0       12    33.0   2       0     0.0   
4         2      23   30        1        9    30.0   1       2     0.0   
..      ...     ...  ...      ...      ...     ...  ..     ...     ...   
995       3      10   39        0        0    27.0   3       0     0.0   
996       1       7   34        0        2    22.0   5       5     0.0   
997       3      67   59        0       40   944.0   5      33     0.0   
998       3      70   49        0       18    87.0   2      22     0.0   
999       3      50   36        1        7    39.0   3       3     0.0   

     gender  reside  custcat  
0         0       2        1  
1         0       6        4  
2         1       2        3  
3         1       1        1  
4         0       4        3  
..      ...     ...      ...  
995       1       3        1  
996       1       1        1  
997       1       1        4  
998       1       1        3  
999       1       3        2  

[1000 rows x 12 columns]

Plotting histogram for customer category with their label

In [4]:
kl = df['custcat']


In [5]:
# Replacing some values in kl
kl=kl.replace({1:'Basic-service',2:'E-Service customers',3:'Plus Service',4:'Total Service'})

In [6]:
kl.iplot(kind='hist')

# FEATURES SETS
Let Define the feature sets:X

In [7]:
# Finding the total columns in the dataset
df.columns

Index(['region', 'tenure', 'age', 'marital', 'address', 'income', 'ed',
       'employ', 'retire', 'gender', 'reside', 'custcat'],
      dtype='object')

To use scikit-learn library, we have to convert the Pandas data frame to a Numpy array:

In [8]:
X = df[['region', 'tenure', 'age', 'marital', 'address', 'income', 'ed',
        'employ', 'retire', 'gender', 'reside']] .values  # .astype(float)
X


array([[ 2., 13., 44., ...,  0.,  0.,  2.],
       [ 3., 11., 33., ...,  0.,  0.,  6.],
       [ 3., 68., 52., ...,  0.,  1.,  2.],
       ...,
       [ 3., 67., 59., ...,  0.,  1.,  1.],
       [ 3., 70., 49., ...,  0.,  1.,  1.],
       [ 3., 50., 36., ...,  0.,  1.,  3.]])

In [9]:
y= df['custcat'].values
y[0:5]

array([1, 4, 3, 1, 3], dtype=int64)

# NORMALIZE THE DATASET
We use standardscaler to Normalize the dataset

In [10]:
# Importing Standardscaler Library
from sklearn import preprocessing

In [11]:
X =  preprocessing.StandardScaler().fit(X).transform(X.astype(float))

# Train and Test Split the Data
This will provide a more accurate evaluation on out-of-sample accuracy because the testing dataset is not part of the dataset that have been used to train the data. It is more realistic for real world problems.

In [12]:
# Importing the sklearn model for train_test_split
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,y_train,y_test= train_test_split(X,y, test_size=0.2, random_state=4)


# Note
We have 1000 rows in the df(dataframe),
We than set the train size to 80% (800 rows) of the dataset and
<p>Set the remaining 20%(200 rows ) as our test_set </p>


In [25]:
print('Train Set', X_train.shape, y_train.shape)
print('Test Set', X_test.shape,y_test.shape)

Train Set (800, 11) (800,)
Test Set (200, 11) (200,)


# PERFORMING CLASSIFCATION 
K-NN (K-Nearest Neighbor)

In [15]:
# Importing the library
from sklearn.neighbors import KNeighborsClassifier

Training the Model
<p> Setting the value of K=4</p>

In [28]:
k=4
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
print(neigh)

KNeighborsClassifier(n_neighbors=4)


# Predicting the Model
We can use the above model to predict the test set

In [31]:
nped = neigh.predict(X_test)
nped[0:5]

array([1, 1, 3, 2, 4], dtype=int64)

# Accuracy Evaluation


In [35]:
from sklearn import metrics
print('Train Set Accuracy', metrics.accuracy_score(y_train,neigh.predict(X_train)))
print('Test Set Accuracy', metrics.accuracy_score(y_test,nped))

Train Set Accuracy 0.5475
Test Set Accuracy 0.32


## Practice
Can you build the model again, but this time with k=6?

In [39]:
from sklearn.neighbors import KNeighborsClassifier

In [59]:
k=5
neigh1 = KNeighborsClassifier(n_neighbors=k).fit(X_train,y_train)
neigh1

KNeighborsClassifier()

In [62]:
print('Train Set Accuracy', metrics.accuracy_score(y_train,neigh1.predict(X_train)))
print('Test Set Accuracy', metrics.accuracy_score(y_test, neigh1.predict(X_test)))

Train Set Accuracy 0.5375
Test Set Accuracy 0.315
